### PR TITLE
[FEAT] Sign in component

### PR DESCRIPTION
**Pull request by karsheng**
1.  FE - Added the  Signin component and updated the Layout component to reflect auth
2. Added a `supabase.js` file to instantiate and export the `supabase` instance.
3.  Export the functions in `src/api` and an `index.js` to manage the exports.

### CODE REVIEW

**Comment by karsheng** [comment]
@kyipho can you take a look at this and see if it's okay to merge.

**Comment by karsheng** [comment]
@kyipho Can you take a look and see if it's okay to merge? You can disregard the FE unless you're interested.

**Comment by kyipho** [comment]
Just a question on a small matter: Is the Supabase export file (`Supabase.js`) title-cased by FE convention? It's lower-cased in your comment so not sure which is the norm.

Regarding the updates in `storage.js`, they're on different lines so I believe there shouldn't be any merge conflicts, but if there are, then you can always pull the latest version first before pushing it.

But otherwise, LGTM! Go ahead and merge it :) I didn't look much into the FE side, but happy to have a crash course some time haha

**Review by kyipho — APPROVED** [review]

**Comment by karsheng** [comment]
> Just a question on a small matter: Is the Supabase export file (`Supabase.js`) title-cased by FE convention? It's lower-cased in your comment so not sure which is the norm.

You're right. It makes more sense to name it lowercase since it's not a React component, which by convention is title-cased. New commit fixes this.

**Pull request merged**
